#:schema node_modules/wrangler/config-schema.json
name = "webp-converter"
main = "src/index.js"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[vars]
IMG_HOST = "static.monsoontea.co.th"

[observability.logs]
enabled = true
